# Generated by Django 6.0.1 on 2026-01-07 22:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reuniao',
            name='convidado',
        ),
        migrations.AddField(
            model_name='reuniao',
            name='convidados',
            field=models.ManyToManyField(related_name='reunioes_convidadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
