# Generated by Django 6.0.1 on 2026-01-08 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tarefa_criador'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='tipo',
            field=models.CharField(choices=[('Estudante', 'Estudante'), ('Mentor', 'Mentor')], default='Estudante', max_length=20, verbose_name='Tipo de Usuário'),
        ),
    ]
