# Generated by Django 6.0.1 on 2026-01-29 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_comentario_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade/Estado'),
        ),
    ]
